### ISSUE TITLE
Fatal error..

### ISSUE THREAD

**Issue by metuza** [DecomTeam/giftable-for-woocommerce#1]
Added a new simple product today and had to deactivate giftable plugin because of the below fatal error when i was to save the simple product:
[04-May-2018 17:25:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Product_Simple::get_visible_children() in /xxxxx/wp-content/plugins/giftable-for-woocommerce/admin/ScreenEditProduct.php:196
Stack trace:
#0 /xxxxx/wp-content/plugins/giftable-for-woocommerce/admin/ScreenEditProduct.php(160): DGFW_ScreenEditProduct::save_giftable_variations(15693)
#1 /xxxxx/wp-includes/class-wp-hook.php(288): DGFW_ScreenEditProduct->save_gift_options(15693, Object(WP_Post))
#2 /xxxxx/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /xxxxx/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /xxxxx/wp-includes/post.php(3570): do_action('save_post_produ...', 15693, Object(WP_Post), true)
#5 /xxxxx/wp-includes/post.php(3654): wp_insert_post(Array, false)
#6 /xxxxx/wp-admin/includes/post.php(377): wp_update_post(Array)
#7 /xxxxx/wp-admin/post.php in /home/www/arctic-fritid.no/wp-content/plugins/giftable-for-woocommerce/admin/ScreenEditProduct.php on line 196``

**Comment by apsolut** [comment]
Just to be sure there are some requirements:
1. PHP minimum version PHP5.6
2. WooCommerce minimum verion 3.x
3. Its variable product you are adding ? with SKU for every variation ?
*will try to check whats with: get_visible_children()

**Comment by metuza** [comment]
1. PHP 7.1
2. Latest WooCommerce
3. Its variable product yes.

Normally i have used to enter a title then set product as variable and then saved. Then the fatal error appear.

But if i fill in all info for 1 variable like sku, price etc. then everything works fine.

So doing it in a new way it works, but the old way as always used it give fatal error.

**Comment by apsolut** [comment]
Thank you for reporting this, its good that you have a way to bypass error,
will try to find time to check that part (adding, removing, saving) variable product in backend

**Comment by mjdewitt** [comment]
Hi,

I ran into this same error and not sure why this is an issue now. I made the following change which seems to work:

    public static function save_giftable_variations($product_id)
    {
        $product = wc_get_product( $product_id );
//      $children = $product->get_visible_children();  <==error line
      $children = $product->get_children(true); // <==True forces "visible"
.
.
.
Mike

**Comment by apsolut** [comment]
hi @mjdewitt  could be that they changed something with `get_visible_children` , will investigate that thing with new version of WC

**Comment by apsolut** [comment]
This should be fixed in `v1.0.4 `
