### ISSUE TITLE
The free gift didnt disable after coupon used

### ISSUE THREAD

**Issue by wwmummygrab** [DecomTeam/giftable-for-woocommerce#3]
The product is RM398

Free Gift rule is above RM300

But coupon discount used is -RM200

So, customer end up pay RM198 BUT still get the Free Gift for above RM300 purchase

how to solve the problem ?

**Comment by apsolut** [comment]
We dont support coupon codes, you can look at **sample code** here:
https://github.com/apsolut/decom-small-giftable-coupon-alternative
